import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://axogabedvxdwvhrjcjpq.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4b2dhYmVkdnhkd3ZocmpjanBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkzMzA0MzMsImV4cCI6MjA0NDkwNjQzM30.aBkJStf8NEai5MYC2xKUWalaWhgQKDMXnl5uA9T4J8s')